/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cricket_db;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Component;
/**
 *
 * @author Bhavith
 */
public class Login extends javax.swing.JFrame {
    private Component btnNewButton;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JPanel();
        LoginTab1 = new javax.swing.JPanel();
        UserField1 = new javax.swing.JTextField();
        PassField1 = new javax.swing.JPasswordField();
        UserLabel1 = new javax.swing.JLabel();
        PassLabel1 = new javax.swing.JLabel();
        Newacc1 = new javax.swing.JButton();
        LoginButton1 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(1000, 6));

        Back.setBackground(new java.awt.Color(0, 102, 153));
        Back.setForeground(new java.awt.Color(36, 22, 43));

        LoginTab1.setBackground(new java.awt.Color(0, 153, 153));
        LoginTab1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 1, 36), new java.awt.Color(0, 0, 51))); // NOI18N

        UserField1.setBackground(new java.awt.Color(255, 237, 243));
        UserField1.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        UserField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });

        PassField1.setBackground(new java.awt.Color(255, 237, 243));
        PassField1.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        UserLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserLabel1.setText("Admin :");

        PassLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PassLabel1.setText("Password :");

        Newacc1.setBackground(new java.awt.Color(204, 204, 204));
        Newacc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Newacc1.setForeground(new java.awt.Color(51, 0, 51));
        Newacc1.setText("Viewer Login");
        Newacc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewaccActionPerformed(evt);
            }
        });

        LoginButton1.setBackground(new java.awt.Color(204, 204, 255));
        LoginButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LoginButton1.setForeground(new java.awt.Color(36, 22, 43));
        LoginButton1.setText("Login");
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginTab1Layout = new javax.swing.GroupLayout(LoginTab1);
        LoginTab1.setLayout(LoginTab1Layout);
        LoginTab1Layout.setHorizontalGroup(
            LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginTab1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginTab1Layout.createSequentialGroup()
                        .addGroup(LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PassLabel1)
                            .addComponent(UserLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserField1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(PassField1))
                            .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginTab1Layout.createSequentialGroup()
                        .addComponent(Newacc1)
                        .addContainerGap())))
        );
        LoginTab1Layout.setVerticalGroup(
            LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginTab1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(LoginTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Newacc1)
                .addContainerGap())
        );

        Exit.setBackground(new java.awt.Color(255, 51, 51));
        Exit.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(51, 0, 51));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap(1409, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(BackLayout.createSequentialGroup()
                .addGap(552, 552, 552)
                .addComponent(LoginTab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(LoginTab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(Exit)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        java.lang.System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String usr = UserField1.getText();
        String pass =new String(PassField1.getPassword());
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
        }
        try
        {
            if(usr.isEmpty()||pass.isEmpty())
            {
                JOptionPane.showMessageDialog(btnNewButton, "Enter Username and Password :)");
                return;
            }
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cric_db","root","bk@1947");
            PreparedStatement st = (PreparedStatement) conn.prepareStatement("Select name, pass from admin where name=? and pass=?");
            st.setString(1, usr);
            st.setString(2, pass);
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                dispose();

                Home obj=new Home();
                obj.setVisible(true);
                setVisible(false);
                JOptionPane.showMessageDialog(btnNewButton,"You have successfully logged in.");
            } 
            else 
            {
                JOptionPane.showMessageDialog(btnNewButton, "Invalid Admin Credentials :)");
                return;
            }

        }
        catch(SQLException sq)
        {
            sq.printStackTrace();
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void NewaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewaccActionPerformed
        VLogin page = new VLogin();
        page.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_NewaccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private javax.swing.JButton Exit;
    private javax.swing.JButton LoginButton1;
    private javax.swing.JPanel LoginTab1;
    private javax.swing.JButton Newacc1;
    private javax.swing.JPasswordField PassField1;
    private javax.swing.JLabel PassLabel1;
    private javax.swing.JTextField UserField1;
    private javax.swing.JLabel UserLabel1;
    // End of variables declaration//GEN-END:variables
}
