/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cricket_db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Bhavith
 */
public class VHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public VHome() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Teams = new javax.swing.JButton();
        Players = new javax.swing.JButton();
        Match = new javax.swing.JButton();
        Coach = new javax.swing.JButton();
        Umpire = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Team_Count = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TPCount = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        title.setBackground(new java.awt.Color(51, 255, 153));
        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 51));
        title.setText("Cricket DB");

        jSeparator1.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator1.setOpaque(true);

        Teams.setBackground(new java.awt.Color(255, 204, 153));
        Teams.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Teams.setForeground(new java.awt.Color(9, 30, 38));
        Teams.setText("Teams");
        Teams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamsActionPerformed(evt);
            }
        });

        Players.setBackground(new java.awt.Color(255, 204, 153));
        Players.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Players.setForeground(new java.awt.Color(9, 30, 38));
        Players.setText("Players");
        Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayersActionPerformed(evt);
            }
        });

        Match.setBackground(new java.awt.Color(255, 204, 153));
        Match.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Match.setForeground(new java.awt.Color(9, 30, 38));
        Match.setText("Matches");
        Match.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatchActionPerformed(evt);
            }
        });

        Coach.setBackground(new java.awt.Color(255, 204, 153));
        Coach.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Coach.setForeground(new java.awt.Color(9, 30, 38));
        Coach.setText("Coaches");
        Coach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachActionPerformed(evt);
            }
        });

        Umpire.setBackground(new java.awt.Color(255, 204, 153));
        Umpire.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Umpire.setForeground(new java.awt.Color(9, 30, 38));
        Umpire.setText("Umpire");
        Umpire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmpireActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(153, 204, 255));
        Logout.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Logout.setForeground(new java.awt.Color(9, 30, 38));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(255, 237, 243));
        Home.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Home.setForeground(new java.awt.Color(9, 30, 38));
        Home.setText("Home");

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setLabelFor(Team_Count);
        jLabel2.setText("Number Of Teams :");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setLabelFor(jScrollPane2);
        jLabel3.setText("Number Of Players In Each Team :");
        jLabel3.setOpaque(true);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\DBMS Project\\Icons\\teams.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\DBMS Project\\Icons\\pla.png")); // NOI18N
        jLabel4.setLabelFor(Players);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\DBMS Project\\Icons\\mat.png")); // NOI18N
        jLabel5.setLabelFor(Match);
        jLabel5.setIconTextGap(0);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\DBMS Project\\Icons\\co.png")); // NOI18N
        jLabel6.setIconTextGap(0);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\DBMS Project\\Icons\\ump.png")); // NOI18N
        jLabel7.setLabelFor(Umpire);
        jLabel7.setIconTextGap(0);

        Team_Count.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Team_Count.setForeground(new java.awt.Color(0, 0, 51));
        Team_Count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team_CountActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TPCount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TPCount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Team_ID", "Team_Name", "No of Players"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TPCount.setRowHeight(30);
        jScrollPane2.setViewportView(TPCount);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 684, Short.MAX_VALUE)
                                .addComponent(title)
                                .addGap(551, 551, 551)
                                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Teams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Match, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Umpire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jLabel7)))
                                    .addComponent(Coach)
                                    .addComponent(Players, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)))
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Team_Count))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(Logout))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team_Count)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Teams)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Players)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Match)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Coach)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Umpire)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamsActionPerformed
              VTeams obj= new VTeams();
              obj.setVisible(true);
              setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_TeamsActionPerformed

    private void PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayersActionPerformed
        VPlayers p = new VPlayers();
        p.setVisible(true);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_PlayersActionPerformed

    private void MatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatchActionPerformed
        VMatches m=new VMatches();
        m.setVisible(true);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_MatchActionPerformed

    private void CoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachActionPerformed
        VCoaches c=new VCoaches();
        c.setVisible(true);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_CoachActionPerformed

    private void UmpireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmpireActionPerformed
            VUmpire u=new VUmpire();
            u.setVisible(true);
            setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_UmpireActionPerformed

    private void Team_CountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team_CountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Team_CountActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        VLogin obj= new VLogin();
        obj.setVisible(true);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed
    public void display()
    {
        try{
            
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cric_db","root", "bk@1947");
            PreparedStatement dst = (PreparedStatement) connection.prepareStatement("select t.team_id as Team_ID,t.tname as Team ,count(p.pid) as No_of_Players from teams t,players p where t.team_id=p.team_id group by (team_id);");
            ResultSet res=dst.executeQuery();
            TPCount.setModel(DbUtils.resultSetToTableModel(res));
            TPCount.setEnabled(false);
            PreparedStatement st = (PreparedStatement) connection.prepareStatement("select count(team_id) from teams;");
            ResultSet res1=st.executeQuery();
            while(res1.next()){
                 Team_Count.setText(res1.getString("count(team_id)"));
                 Team_Count.setEditable(false);
            }
            
            
        }
        catch(Exception sqlException){
            sqlException.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Coach;
    private javax.swing.JButton Home;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Match;
    private javax.swing.JButton Players;
    private javax.swing.JTable TPCount;
    private javax.swing.JTextField Team_Count;
    private javax.swing.JButton Teams;
    private javax.swing.JButton Umpire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
